### ISSUE TITLE
Badge links are not working with new search.maven.org site

### ISSUE THREAD

**Issue by ferstl** [softwaremill/maven-badges#20] opened 2018-08-09 10:06 UTC
There was a redesign of https://search.maven.org . Since then clicking on a badge leads to the search page and not to the artifact page anymore.

Example:
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/cz.jirutka.rsql/rsql-parser/badge.svg?style=plastic)](https://maven-badges.herokuapp.com/maven-central/cz.jirutka.rsql/rsql-parser)

**Comment by DarthHater** [comment] 2018-08-09 16:57
Hi there,

So you can do two things here:

- Update the URL to have /classic/ in it (this will take you to the old site), and is likely the easiest for just getting things working as they were
- Update the URL to match a pattern like this: https://search.maven.org/artifact/org.robolectric/junit/4.0-alpha-3/jar

That should get you fixed up!

**Comment by lukaszlenart** [comment] 2018-08-27 07:30
PR got merged, I'm closing this issue for now.

**Closed by lukaszlenart** 2018-08-27 07:30 UTC

**Comment by ferstl** [comment] 2018-09-07 12:31
Thank you! Works fine again.

**Comment by brunchboy** [comment] 2018-10-03 01:49
It’s not working for me with the old links, it just takes me to an empty search page. And the suggestion of embedding a direct link to the search page as above doesn’t help me, as I rely on your application to take people to the latest released version; if I have to embed a version in the URL, then I have to remember to update my README every time I do a release, which defeats the whole purpose of using this badge. Is there any hope of getting this working again?

**Comment by brunchboy** [comment] 2018-10-03 02:35
Oh, I think I misunderstood @DarthHater’s comment to be instructions to me on how I could change links on my own project page where I am using the badge, but looking more closely, I think they were instructions to this project on how to fix the links generated by the badge itself.

Either way, though, the links from my badges (for example, [here](https://github.com/brunchboy/electro#electro)) are not working, and nor is the one at the top in the original issue report. Should I open this as a new issue?

**Comment by lukaszlenart** [comment] 2018-10-03 05:35
Hm.. but it works, I have clicked on the link and I was redirect to
https://search.maven.org/artifact/org.deepsymmetry/electro/0.1.3/jar

**Comment by brunchboy** [comment] 2018-10-03 14:17
Weird, maybe there is something wrong at a Content Delivery Network, then? I was still getting taken to the main Search page with nothing filled in. I just tried clearing my browser caches, and now I get taken to a blank page. Digging more deeply, I am still getting redirected to the wrong place:

```
 curl -v https://maven-badges.herokuapp.com/maven-central/org.deepsymmetry/electro
*   Trying 52.202.245.247...
* TCP_NODELAY set
* Connected to maven-badges.herokuapp.com (52.202.245.247) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Heroku, Inc.; CN=*.herokuapp.com
*  start date: Apr 19 00:00:00 2017 GMT
*  expire date: Jun 22 12:00:00 2020 GMT
*  subjectAltName: host "maven-badges.herokuapp.com" matched cert's "*.herokuapp.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /maven-central/org.deepsymmetry/electro HTTP/1.1
> Host: maven-badges.herokuapp.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: Cowboy
< Connection: keep-alive
< X-Powered-By: Express
< Location: http://search.maven.org/#artifactdetails%7Corg.deepsymmetry%7Celectro%7C0.1.3%7C
< Vary: Accept
< Content-Type: text/plain; charset=utf-8
< Content-Length: 102
< Date: Wed, 03 Oct 2018 14:13:26 GMT
< Via: 1.1 vegur
< 
* Connection #0 to host maven-badges.herokuapp.com left intact
Found. Redirecting to http://search.maven.org/#artifactdetails%7Corg.deepsymmetry%7Celectro%7C0.1.3%7C
```

**Comment by lukaszlenart** [comment] 2018-10-04 06:53
You must use a proper browser because this is a JS based solution (at search.maven.org) and the url is constructed using JS code.

Try to use anonymous window to see if it works.

**Comment by brunchboy** [comment] 2018-10-04 13:46
I don’t follow… I was showing you the interaction between curl and maven-badges.herokuapp.com, and it looked like the wrong, old-style redirect was being delivered by maven-badges.herokuapp.com. The JS at search.maven.org did not even have a chance to get involved.

It doesn’t matter whether I use an ordinary or private window, and even after deleting my caches again and all website data for github.com and maven.org, the badge takes me only to the blank search page in Safari. It seems to work in Chrome, but not Safari.

**Comment by lukaszlenart** [comment] 2018-10-04 14:00
Please see the capture of my screen and redirects that happens, there are at least three url changes where just one is made by the maven-badges project. The rest happens on the search.maven.org side using JS.

![badges](https://user-images.githubusercontent.com/170103/46478874-244d7500-c7ee-11e8-890f-5eda0ec6e086.gif)

**Comment by brunchboy** [comment] 2018-10-04 18:01
Sorry, I was rushing out the door, and was too brief, I think we are talking past each other a bit. I agree that the problem now seems to be on the search.maven.org side, since their JavaScript redirect does not work properly with Safari, though it does work (even for me) with Chrome. It may be possible to get them to fix that, I can try to figure out how to open a ticket with them if I need to, although it sounds like your team may already have a relationship with them that would make that easier.

However, surely we could avoid that problem entirely if maven-badges generated a redirect using the new format that search.maven.org wants, rather than the old format that gets redirected? If I send Safari to https://search.maven.org/artifact/org.deepsymmetry/electro/0.1.3/jar it works fine, but if I send it to http://search.maven.org/#artifactdetails%7Corg.deepsymmetry%7Celectro%7C0.1.3%7C it does not. And that, it seems to me, is within the control of maven-badges, is it not?

**Comment by brunchboy** [comment] 2018-10-04 18:33
I’m having an impossible time trying to trace the redirect process in Safari, unfortunately, so I am losing confidence about what is actually going wrong. And over SSL, I can’t even use a network traffic capture to help much with that.

I’m just worried that most of the users of my projects, many of whom use Macs and are just starting to dabble in development will be using the default platform browser and will be confused by being taken to an empty search page when they want to look for instructions on how to embed my Maven artifacts using their language of choice. I loved being able to send people to the artifact pages.

**Comment by DarthHater** [comment] 2018-10-04 18:36
I think y'all need to update to use the new artifact URL that I posted earlier. I would do that, the changes we made to support the old URLs loading on the new site is a JS solution and is obviously prone to browsers being funky.

**Comment by brunchboy** [comment] 2018-10-25 21:00
Please consider doing as @DarthHater suggests, because otherwise nobody using Safari (the standard browser on MacOS and iOS) will get taken to the right place when clicking on a badge.

**Comment by brunchboy** [comment] 2018-10-26 16:07
He and I are requesting that you not rely on JavaScript on the Maven site to update the outdated URL format to the correct new format he described on August 9, since the JavaScript workaround does not work in all standard browsers. In other words, instead of generating URLs like:

```
http://search.maven.org/#artifactdetails%7Corg.deepsymmetry%7Celectro%7C0.1.3%7C
```

Generate URLs like this:

```
https://search.maven.org/artifact/org.deepsymmetry/electro/0.1.3/jar
```

What is strange to me is that it looks like the [source code](https://github.com/softwaremill/maven-badges/blob/c44cc7a49e76c558d1ad45abdb790b2bc7d860e0/src/services/mavenCentral.ts#L30-L31) should be doing it the new, correct, way, and yet when I `curl` from maven-badges.herokuapp.com I still see the old response.

**Comment by lukaszlenart** [comment] 2018-10-27 07:11
The problem is that it isn't possible to `/solsearch` now and you will be redirect to the normal search page, [see this code](https://github.com/softwaremill/maven-badges/blob/master/src/services/mavenCentral.ts#L12-L19)

https://search.maven.org/solsearch/select?q=g:%22org.apache.struts%22a:%22struts2-core%22&rows=1&wt=json

**Comment by lukaszlenart** [comment] 2018-10-27 07:13
Maybe it is related to [CORS](https://github.com/sonatype-nexus-community/search-maven-org/#data)

**Comment by lukaszlenart** [comment] 2018-10-27 07:31
Looks good, please use Safari to test this url https://maven-badges.herokuapp.com/maven-central/cz.jirutka.rsql/rsql-parser

**Comment by brunchboy** [comment] 2018-10-27 07:32
I get taken to the proper details page, thank you! My own Git badges are fixed as well. 😁
